"""
CheckBundle: CUP008 — stale __init__.py bundle detection.
"""

from pathlib import Path

from codeupipe import Payload


class CheckBundle:
    """
    Filter (sync): Detect modules missing from a cup-bundle generated __init__.py.

    Input keys:
        - directory (str): path to the scanned directory
        - files (list[dict]): file analyses from ScanDirectory
        - issues (list): accumulated lint issues

    Output keys (modified):
        - issues (list): with CUP008 violations appended
    """

    def call(self, payload: Payload) -> Payload:
        directory = payload.get("directory")
        files = payload.get("files", [])
        issues = list(payload.get("issues", []))

        dir_path = Path(directory)
        init_file = dir_path / "__init__.py"

        if not init_file.exists():
            return payload.insert("issues", issues)

        init_content = init_file.read_text()
        if "Auto-generated by: cup bundle" not in init_content:
            return payload.insert("issues", issues)

        for info in files:
            module = info["stem"]
            if f"from .{module} import" not in init_content:
                issues.append((
                    "CUP008", "warning", str(init_file),
                    f"Bundle is stale: module '{module}' not exported. "
                    f"Run: cup bundle {directory}"
                ))

        return payload.insert("issues", issues)
