"""Integration tests for the CUP linter pipeline (dogfooding)."""

import asyncio

import pytest

from codeupipe import Payload
from codeupipe.linter.lint_pipeline import build_lint_pipeline


def run(coro):
    return asyncio.run(coro)


class TestLintPipeline:
    """Integration tests for the composed lint pipeline."""

    def test_clean_directory_no_issues(self, tmp_path):
        (tmp_path / "validate_email.py").write_text(
            "class ValidateEmail:\n    def call(self, p): return p\n"
        )
        tests_dir = tmp_path / "tests"
        tests_dir.mkdir()
        (tests_dir / "test_validate_email.py").write_text("# test\n")
        pipeline = build_lint_pipeline()
        result = run(pipeline.run(Payload({
            "directory": str(tmp_path),
            "tests_dir": str(tests_dir),
        })))
        assert result.get("issues") == []

    def test_state_tracks_all_six_steps(self, tmp_path):
        (tmp_path / "a.py").write_text("x = 1\n")
        pipeline = build_lint_pipeline()
        run(pipeline.run(Payload({"directory": str(tmp_path)})))
        executed = pipeline.state.executed
        assert "scan_directory" in executed
        assert "check_naming" in executed
        assert "check_structure" in executed
        assert "check_protocols" in executed
        assert "check_tests" in executed
        assert "check_bundle" in executed

    def test_catches_naming_violation(self, tmp_path):
        (tmp_path / "BadName.py").write_text("class BadName:\n    def call(self, p): return p\n")
        pipeline = build_lint_pipeline()
        result = run(pipeline.run(Payload({"directory": str(tmp_path)})))
        rules = [i[0] for i in result.get("issues")]
        assert "CUP007" in rules

    def test_catches_multi_component_violation(self, tmp_path):
        (tmp_path / "multi.py").write_text(
            "class A:\n    def call(self, p): return p\n"
            "class B:\n    def observe(self, p): pass\n"
        )
        pipeline = build_lint_pipeline()
        result = run(pipeline.run(Payload({"directory": str(tmp_path)})))
        rules = [i[0] for i in result.get("issues")]
        assert "CUP001" in rules

    def test_catches_protocol_violation(self, tmp_path):
        (tmp_path / "broken.py").write_text(
            "class Broken:\n    def call(self, p): return p\n"
            "    # has call but we'll check a hook\n"
        )
        # Create a hook missing methods
        (tmp_path / "bad_hook.py").write_text(
            "class BadHook(Hook):\n    pass\n"
        )
        pipeline = build_lint_pipeline()
        result = run(pipeline.run(Payload({"directory": str(tmp_path)})))
        rules = [i[0] for i in result.get("issues")]
        assert "CUP006" in rules

    def test_catches_missing_test(self, tmp_path):
        (tmp_path / "my_filter.py").write_text("class MyFilter:\n    def call(self, p): return p\n")
        pipeline = build_lint_pipeline()
        result = run(pipeline.run(Payload({"directory": str(tmp_path)})))
        rules = [i[0] for i in result.get("issues")]
        assert "CUP002" in rules

    def test_catches_stale_bundle(self, tmp_path):
        (tmp_path / "__init__.py").write_text("# Auto-generated by: cup bundle\n")
        (tmp_path / "orphan.py").write_text("x = 1\n")
        pipeline = build_lint_pipeline()
        result = run(pipeline.run(Payload({"directory": str(tmp_path)})))
        rules = [i[0] for i in result.get("issues")]
        assert "CUP008" in rules

    def test_catches_syntax_error(self, tmp_path):
        (tmp_path / "bad.py").write_text("def broken(\n")
        pipeline = build_lint_pipeline()
        result = run(pipeline.run(Payload({"directory": str(tmp_path)})))
        rules = [i[0] for i in result.get("issues")]
        assert "CUP000" in rules

    def test_multiple_violations_accumulated(self, tmp_path):
        # PascalCase name + multiple components + missing test
        (tmp_path / "BadFile.py").write_text(
            "class Alpha:\n    def call(self, p): return p\n"
            "class Beta:\n    def observe(self, p): pass\n"
        )
        pipeline = build_lint_pipeline()
        result = run(pipeline.run(Payload({"directory": str(tmp_path)})))
        rules = [i[0] for i in result.get("issues")]
        assert "CUP007" in rules  # naming
        assert "CUP001" in rules  # structure
        assert "CUP002" in rules  # missing test

    def test_directory_not_found(self, tmp_path):
        pipeline = build_lint_pipeline()
        with pytest.raises(FileNotFoundError):
            run(pipeline.run(Payload({"directory": str(tmp_path / "nope")})))

    def test_pipeline_returns_payload(self, tmp_path):
        (tmp_path / "a.py").write_text("x = 1\n")
        pipeline = build_lint_pipeline()
        result = run(pipeline.run(Payload({"directory": str(tmp_path)})))
        assert result.get("directory") == str(tmp_path)
        assert isinstance(result.get("files"), list)
        assert isinstance(result.get("issues"), list)

    def test_lints_own_package(self):
        """The linter can lint its own source (dogfooding meta-test)."""
        pipeline = build_lint_pipeline()
        result = run(pipeline.run(Payload({"directory": "codeupipe/linter"})))
        assert result.get("issues") == []
