"""Tests for CheckBundle filter."""

import pytest

from codeupipe import Payload
from codeupipe.linter.check_bundle import CheckBundle


class TestCheckBundle:
    """Unit tests for CheckBundle filter."""

    def test_no_init_file_passes(self, tmp_path):
        files = [{"path": str(tmp_path / "a.py"), "stem": "a", "classes": [], "functions": [], "error": None}]
        payload = Payload({"directory": str(tmp_path), "files": files, "issues": []})
        result = CheckBundle().call(payload)
        assert result.get("issues") == []

    def test_non_cup_init_passes(self, tmp_path):
        (tmp_path / "__init__.py").write_text("# manual init\n")
        files = [{"path": str(tmp_path / "a.py"), "stem": "a", "classes": [], "functions": [], "error": None}]
        payload = Payload({"directory": str(tmp_path), "files": files, "issues": []})
        result = CheckBundle().call(payload)
        assert result.get("issues") == []

    def test_fresh_bundle_passes(self, tmp_path):
        init_content = '# Auto-generated by: cup bundle\nfrom .my_filter import MyFilter\n'
        (tmp_path / "__init__.py").write_text(init_content)
        files = [{"path": str(tmp_path / "my_filter.py"), "stem": "my_filter", "classes": [], "functions": [], "error": None}]
        payload = Payload({"directory": str(tmp_path), "files": files, "issues": []})
        result = CheckBundle().call(payload)
        assert result.get("issues") == []

    def test_stale_bundle_flagged(self, tmp_path):
        init_content = '# Auto-generated by: cup bundle\nfrom .old_filter import OldFilter\n'
        (tmp_path / "__init__.py").write_text(init_content)
        files = [
            {"path": str(tmp_path / "old_filter.py"), "stem": "old_filter", "classes": [], "functions": [], "error": None},
            {"path": str(tmp_path / "new_filter.py"), "stem": "new_filter", "classes": [], "functions": [], "error": None},
        ]
        payload = Payload({"directory": str(tmp_path), "files": files, "issues": []})
        result = CheckBundle().call(payload)
        issues = result.get("issues")
        assert len(issues) == 1
        assert issues[0][0] == "CUP008"
        assert issues[0][1] == "warning"
        assert "new_filter" in issues[0][3]

    def test_multiple_stale_modules(self, tmp_path):
        (tmp_path / "__init__.py").write_text("# Auto-generated by: cup bundle\n")
        files = [
            {"path": str(tmp_path / "a.py"), "stem": "a", "classes": [], "functions": [], "error": None},
            {"path": str(tmp_path / "b.py"), "stem": "b", "classes": [], "functions": [], "error": None},
        ]
        payload = Payload({"directory": str(tmp_path), "files": files, "issues": []})
        result = CheckBundle().call(payload)
        issues = result.get("issues")
        assert len(issues) == 2
        modules = [i[3] for i in issues]
        assert any("'a'" in m for m in modules)
        assert any("'b'" in m for m in modules)

    def test_preserves_existing_issues(self, tmp_path):
        (tmp_path / "__init__.py").write_text("# Auto-generated by: cup bundle\n")
        files = [{"path": str(tmp_path / "x.py"), "stem": "x", "classes": [], "functions": [], "error": None}]
        payload = Payload({
            "directory": str(tmp_path),
            "files": files,
            "issues": [("OLD", "warn", "/", "old")],
        })
        result = CheckBundle().call(payload)
        assert result.get("issues")[0][0] == "OLD"

    def test_empty_files_fresh_bundle(self, tmp_path):
        (tmp_path / "__init__.py").write_text("# Auto-generated by: cup bundle\n")
        payload = Payload({"directory": str(tmp_path), "files": [], "issues": []})
        result = CheckBundle().call(payload)
        assert result.get("issues") == []
